### ISSUE TITLE
accept multiple column columns 

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tlang#76]

**Comment by bzkrouse** [comment]
summarizing a chat w/ @thebioengineer:
Multiple columns not only allows user to pass spanning labels via the dataset but it also allows you to avoid having to concatenate things into a single column of unique values in the ARD
Our previous thought was pivot on multiple vars & use tab_spanner_delim, but looks like we are moving away from that due to limitations. However, we cannot pivot_wider unless we pivot on multiple columns or concatenate them pre-pivot. 
How should this be handled? do we have a strict requirement for a lowest level column that is unique? Should we pull out the column info and use indices for the pivot?
